//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8784
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupDelayed.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartupDelayed.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addfont; Arial;9;Bold;Group;
        ///addfont; Microsoft Sans Serif;8;Regular;Names;
        ///addfont; Arial;14;Bold;Slogan;
        ///
        ///scene;20;
        ///addstring;IP Informer;Group;
        ///addstring;v 0.1.2;Group;
        ///addstring;Распространяется бесплатно;Names;
        ///addstring;                      ;Names;
        ///addstring;Developers;Group;
        ///addstring;[Wildsoft], [Chaos Software];Group;
        ///addstring;                      ;Names;
        ///addstring;Idea by;Group;
        ///addstring;OPPosition;Names;
        ///addstring;Code by;Group;
        ///addstring;Hex_Laden;Names;
        ///addstring;Chang Min H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ani01 {
            get {
                object obj = ResourceManager.GetObject("ani01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ani02 {
            get {
                object obj = ResourceManager.GetObject("ani02", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ani03 {
            get {
                object obj = ResourceManager.GetObject("ani03", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ani04 {
            get {
                object obj = ResourceManager.GetObject("ani04", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ani05 {
            get {
                object obj = ResourceManager.GetObject("ani05", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры командной строки:
        ///StartupDelayed /help
        ///StartupDelayed [/run] [/d|confdir &lt;путь&gt;]
        ////help - эта справка
        ////run - выполнение задач
        ////d - запускать в &quot;не-портативном режиме&quot; (конфигурационные файлы в директории %LocalApplicationsData%\StartupDelayed)
        ////confdir &lt;путь&gt; - путь к директории с файлами конфигурации
        ///
        ///По умолчанию программа будет запущена в режиме конфигурации, и будет искать конфигурационные файлы в директории с исполняемым файлом..
        /// </summary>
        internal static string cl_help {
            get {
                return ResourceManager.GetString("cl_help", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
